import logging
from sqlalchemy import text
from sqlglot import parse_one, exp
import sqlalchemy

from text_to_sql_agent.db import engine

from text_to_sql_agent.runtime_bootstrap import FOREIGN_KEYS
from text_to_sql_agent.sql_validation.join_validator import validate_joins

logger = logging.getLogger(__name__)
sql_logger = logging.getLogger("text_to_sql_agent.sql")

class HardTermination(Exception):
    """
    Raised when the system must immediately stop execution.
    """
    pass


def extract_tables(sql: str) -> set[str]:
    """
    Extract table names from a SQL query.

    Args:
        sql: SQL string.

    Returns:
        Set of table names.
    """
    tree = parse_one(sql, read="sqlite")
    return {t.name.lower() for t in tree.find_all(exp.Table) if t.name}


def sql_check_tool(query: str) -> str:
    if not query:
        return "INVALID: Empty query."

    normalized = query.strip().lower()

    if not normalized.startswith(("select", "with")):
        return "INVALID: Only SELECT or WITH queries are allowed."

    if "--" in normalized or "/*" in normalized or "*/" in normalized:
        return "INVALID: SQL comments are not allowed."

    # Parse + extract tables
    try:
        extract_tables(query)
    except Exception:
        return "INVALID: Failed to parse SQL."

    # Join validation (only if joins exist)
    try:
        if " join " in normalized and not validate_joins(query, FOREIGN_KEYS):
            return "INVALID: Join condition does not match schema foreign keys."
    except Exception:
        return "INVALID: Failed to validate join conditions."

    # Final DB-level sanity check
    with engine.connect() as conn:
        try:
            conn.execute(text(f"EXPLAIN QUERY PLAN {query}"))
            return "VALID"
        except sqlalchemy.exc.SQLAlchemyError as e:
            return f"INVALID: {str(e)}"


def sql_exec_tool(query: str):
    """
    Execute a validated SQL query.

    Args:
        query: SQL query.

    Returns:
        Query result rows.

    Raises:
        HardTermination if validation fails.
    """
    sql_logger.info(f"SQL generated by LLM:\n{query}")

    check = sql_check_tool(query)
    if check != "VALID":
        sql_logger.warning(f"SQL Schema validation failed:\n{check}")
        raise HardTermination(check)

    with engine.connect() as conn:
        rows = conn.execute(text(query)).fetchall()
        logger.info("SQL Executed Successfully")
        return rows
