import logging
from sqlalchemy import text
import sqlalchemy

from text_to_sql_agent.db import engine

from text_to_sql_agent.sql_tools.sql_static_checks import sql_static_check

logger = logging.getLogger(__name__)
sql_logger = logging.getLogger("text_to_sql_agent.sql")

class HardTermination(Exception):
    """
    Raised when the system must immediately stop execution.
    """
    pass


def sql_check_tool(query: str) -> str:
    static_check = sql_static_check(query)
    if static_check != "VALID":
        return static_check

    with engine.connect() as conn:
        try:
            conn.execute(text(f"EXPLAIN QUERY PLAN {query}"))
            return "VALID"
        except sqlalchemy.exc.SQLAlchemyError as e:
            return f"INVALID: {str(e)}"


def sql_exec_tool(query: str):
    """
    Execute a validated SQL query.

    Args:
        query: SQL query.

    Returns:
        Query result rows.

    Raises:
        HardTermination if validation fails.
    """
    sql_logger.info(f"SQL generated by LLM:\n{query}")

    check = sql_check_tool(query)
    if check != "VALID":
        sql_logger.warning(f"SQL Schema validation failed:\n{check}")
        raise HardTermination(check)

    with engine.connect() as conn:
        rows = conn.execute(text(query)).fetchall()
        logger.info("SQL Executed Successfully")
        return rows
